// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Roulette.Core.Context;

namespace Roulette.Core.Migrations
{
    [DbContext(typeof(RouletteDbContext))]
    partial class RouletteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Roulette.Core.Bet.Entities.Bet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BetType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PickId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PickId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("Roulette.Core.Bet.Entities.Pick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PickDetailsId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PickDetailsId");

                    b.ToTable("Pick");
                });

            modelBuilder.Entity("Roulette.Core.Bet.Entities.PickDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PickDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PickDetails");
                });

            modelBuilder.Entity("Roulette.Core.Bet.Entities.Bet", b =>
                {
                    b.HasOne("Roulette.Core.Bet.Entities.Pick", "Pick")
                        .WithMany()
                        .HasForeignKey("PickId");

                    b.Navigation("Pick");
                });

            modelBuilder.Entity("Roulette.Core.Bet.Entities.Pick", b =>
                {
                    b.HasOne("Roulette.Core.Bet.Entities.PickDetails", "PickDetails")
                        .WithMany()
                        .HasForeignKey("PickDetailsId");

                    b.Navigation("PickDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
